# Generated by Django 3.0.5 on 2020-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='longer_feature',
            field=models.BooleanField(default=False),
        ),
    ]
